#!/bin/bash
interpreter="$( cat src/buildstep/create_extension_spec.py )"
interpreter_ts="export const interpreter_script = \`$interpreter\`;"

# Generate NWB create_extension_spec.py script as string in TypeScript
echo "
/****
 * This file was auto-generated by build.sh
 * to edit, please edit src/buildstep/create_extension_spec.py
 **/
$interpreter_ts" > src/data/interpreter.ts
echo "Added interpreter script to src/data/interpreter.ts"

# Generate NWB Core types in TypeScript
python3 src/buildstep/gencore-script.py > src/data/nwbcore.ts

echo "Completed build script"