#!/bin/bash

# Build script
# ------------
#   generate typescript string with the exported python script
#   generate typescript NWB catalogue
#   generate all.ts files inside src/inputs, src/forms and src/typeviz

if [ -n "$1" ] && [ "$1" != "-q" ]; then
    echo "USAGE: ./build.sh [-q]"
    exit
fi

# Generate NWB create_extension_spec.py script as string in TypeScript

interpreter="$( cat src/buildstep/create_extension_spec.py )"
interpreter_ts="export const interpreterScript = \`$interpreter\`;"
echo "
/****
 * This file was auto-generated by build.sh
 * to edit, please edit src/buildstep/create_extension_spec.py
 **/
$interpreter_ts" > src/data/interpreter.ts


if [ -z "$1" ]; then
    echo "Added interpreter script to src/data/interpreter.ts"
fi

# Generate all.ts files for inputs and forms to make imports easier

autogen_msg="/**
 * This file was auto-generated by build.sh
 * Please don't edit manually
 **/"

echo "$autogen_msg" > src/inputs/all.ts
echo "$autogen_msg" > src/forms/all.ts
echo "$autogen_msg" > src/typeviz/all.ts

for f in src/inputs/*.ts; do
    if [ "$f" != "src/inputs/all.ts" ]; then
        echo "import './$(basename $f .ts)';" >> src/inputs/all.ts
    fi
done

if [ -z "$1" ]; then
    echo "Generated src/inputs/all.ts:"
    echo "============================"
    cat src/inputs/all.ts
fi

for f in src/forms/*.ts; do
    if [ "$f" != "src/forms/all.ts" ]; then
        echo "import './$(basename $f .ts)';" >> src/forms/all.ts
    fi
done

if [ -z "$1" ]; then
    echo "Generated src/forms/all.ts:"
    echo "==========================="
    cat src/forms/all.ts
fi

for f in src/typeviz/*.ts; do
    if [ "$f" != "src/typeviz/all.ts" ]; then
        echo "import './$(basename $f .ts)';" >> src/typeviz/all.ts
    fi
done

if [ -z "$1" ]; then
    echo "Generated src/typeviz/all.ts:"
    echo "==========================="
    cat src/typeviz/all.ts
fi

# Generate NWB Core types in TypeScript

if [ -z "$1" ]; then
    python3 src/buildstep/gencore-script.py > src/data/nwbcore.ts
else 
    python3 src/buildstep/gencore-script.py > src/data/nwbcore.ts 2> /dev/null
fi

echo "Completed build.sh script"