/**
 * This file was auto-generated by build.sh
 * Please don't edit manually
 **/
import './abstract-input';
import './dtype-input';
import './quantity-or-name';
import './radio-input';
import './shape-input';
import './shape-or-scalar';
import './value-input';
