"""
This file was autogenerated with the NWB extension builder app
It generates the {{"namespace_name"}} extension
"""

from pynwb.spec import *

ns = {{"namespace"}}
types = {{"types"}}
includes = {{"includes"}}

ns_path = ns["name"] + ".namespace.yaml"
ext_source = ns["name"] + ".extensions.yaml"


def gen_types(types):
    return [gen_group_spec(ty) if kind == 'GROUP' else
            gen_dataset_spec(ty) for kind, ty in types]


def gen_group_spec(spec):
    spec["groups"] = [gen_group_spec(g) for g in spec["groups"]]
    spec["datasets"] = [gen_dataset_spec(d) for d in spec["datasets"]]
    spec["attributes"] = [gen_attribute_spec(a) for a in spec["attributes"]]
    spec["links"] = [gen_link_spec(l) for l in spec["links"]]
    return NWBGroupSpec(**spec)


def gen_shape(shape):
    [None if s == "None" else s for s in shape]


def gen_dataset_spec(spec):
    spec["attributes"] = [gen_attribute_spec(a) for a in spec["attributes"]]
    spec["dtype"] = gen_dtype_spec(spec["dtype"])
    spec["shape"] = gen_shape(spec["shape"])
    return NWBDatasetSpec(**spec)


def gen_attribute_spec(spec):
    spec["dtype"] = gen_dtype_spec(spec["dtype"])
    spec["shape"] = gen_shape(spec["shape"])
    return NWBAttributeSpec(**spec)


def gen_dtype_spec(spec):
    if isinstance(spec, str):
        return spec if spec != "None" else None
    elif isinstance(spec, dict) and ['target_type', 'region'] in spec:
        return NWBRefSpec(**spec)
    elif isinstance(spec, dict) and ['name', 'doc', 'dtype'] in spec:
        spec["dtype"] = [gen_dtype_spec(d) for d in spec["dtype"]]
        return NWBDtypeSpec(**spec)


def gen_link_spec(spec):
    return NWBLinkSpec(**spec)


def gen_namespace(ns):
    return NWBNamespaceBuilder(**ns)


ns_builder = gen_namespace(ns)

for inc in includes:
    ns_builder.include_type(inc, namespace="core")

ns_builder.add_spec(
    ext_source, [gen_types(ty) for ty in types]
)

ns_builder.export(ns_path)


"""
Don't worry about the junk below. It has no effect on this script.
It is a signature so that this file can be read back in by the extension 
builder app when you want to make changes.
"""

"""
{{"signature"}}
"""
