/**
 * This file was auto-generated by build.sh
 * Please don't edit manually
 **/
import './abstract-form';
import './attrib-form';
import './axes-form';
import './codegen-form';
import './dtype-form';
import './inctype-form';
import './link-form';
import './name-forms';
import './namespace-forms';
import './typeviz-form';
