
    import * as Spec from "../nwb/spec";

    /*
     * This file is generated by src/data/gencore-script.py.
     * Do not edit.
     */

    function coreQueryAsNWBType(id: string): Spec.NWBType {
        let res = coreQuery(id);
        switch (res[0]) {
            case "GROUP":
            return ["GROUP", ["Core", res[1]]];
            case "DATASET":
            return ["DATASET", ["Core", res[1]]];
            default:
            assertNever(res[0]);
        }
    }

    type CoreTypeId = ["GROUP" | "DATASET", string];
    export function coreQuery(id: string): Spec.CoreType {
        const catalog: { [keyof: string]: Spec.CoreType } = {};
        return catalog[id];
    }
    
    export const modules: { [keyof: string]: CoreTypeId[] } = {};
    

